itnsa/accounts/urls.py
from django.urls import path 
from . import views


app_name = 'accounts'

urlpatterns = [
    path('register/', views.register, name='register'),
]

itnsa/home/urls.py
from django.urls import path

from . import views

# create your urls here

app_name = 'home'

urlpatterns = [
    path('', views.HomePage.as_view(), name='home'),
    path('about/', views.AboutPage.as_view(), name='about'),
]

itnsa/itnsa/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('accounts/', include('accounts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = 'ITNSA'
admin.site.site_title = 'ITNSA'
admin.site.index_title = 'ITNSA'

itnsa/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.contrib.auth.models import Permission
from django.utils.translation import gettext_lazy as _


# Create your models here.

class User(AbstractUser):
    real_name = models.CharField(max_length=50, blank=True)
    phone_number = models.CharField(max_length=20, blank=True)
    is_student = models.BooleanField(default=False)
    is_coach = models.BooleanField(default=False)
    is_competitor = models.BooleanField(default=False)
    is_staff = models.BooleanField(
        _("staff status"),
        default=True,
        help_text=_("Designates whether the user can log into this admin site."),
    )

    class Meta(AbstractUser.Meta):
        pass

    def __str__(self):
        if self.real_name:
            return self.real_name
        return self.username

itnsa/home/models.py
from django.db import models

# Create your models here.

itnsa/tlog/models.py
from unicodedata import name
from django.db import models

# Create your models here.
from django.db import models

from os import path
from datetime import date

from django.db import models
from django.core.files.storage import FileSystemStorage

# Create your models here.

class ClassTypeList(models.TextChoices):
    CLASS = 'CL', '精英班'
    TRAINING = 'TR', '中国集训队'


ROLE_CHOICES = [
    ("Coach", "教练"),
    ("Competitor", "选手"),
    ("Student", "学生"),
]

MODULE_LIST = [
    ("ModuleA", "A模块: ServerClient"),
    ("ModuleB", "B模块: Network"),
    ("ModuleC", "C模块: Python"),
    ("ModuleD", "D模块: TroubleShooting"),
    ("ModuleE", "E模块: English"),
    ("Other", "Other"),
]

# Define user directory path
def user_dierctory_path(instance, filename):
    # 文件扩展名
    ext = filename.split('.')[-1]
    # 作者的角色名字
    for i in ROLE_CHOICES:
        if i[0] == instance.author_role:
            author_role = i[1]
    # 作者的姓名
    author_name = instance.author_name
    # 班级类型的名字
    class_type = ClassTypeList(instance.class_type).label
    class_type_log = f'第46届世界技能大赛网络系统管理项目{class_type}训练日志'
    # 日志的写作日期
    log_date = instance.log_date.strftime("%Y.%m.%d")
    # 模块的名字
    module_list = instance.module_list
    # 文件名重命名的组合方式
    filename_parts = [author_role, class_type_log,
                      module_list, author_name, log_date]
    filename = '-'.join(filename_parts) + '.' + ext
    # filename = '{}.{}'.format(uuid.uuid4().hex[:10], ext)
    return path.join(
                        "tlogs",
                        log_date.split('.')[0], 
                        log_date.split('.')[1], 
                        log_date.split('.')[2], 
                        filename
                        )



# remove log_file if exists when it upload.
class OverwriteStorage(FileSystemStorage):
    def get_available_name(self, name, max_length=None):
        if self.exists(name):
            self.delete(name)
        return name


class LogUploadModel(models.Model):
    user = models.ForeignKey(
        'accounts.User',
        on_delete=models.CASCADE,
     )
    author_name = models.CharField(
        max_length=10,
        null=False,
        blank=False,
        verbose_name="作者"
    )
    # author_name = models.OneToOneField(
    #     'accounts.User',
    #     on_delete=models.CASCADE,
    #     verbose_name="作者"
    # )

    # name = models.CharField(
    #     max_length=10,
    #     # default=get_username,
    #     verbose_name="作者"
    # )

    author_role = models.CharField(
        max_length=10,
        choices=ROLE_CHOICES,
        default="Competitor",
        blank=False,
        verbose_name="角色"
    )
    log_date = models.DateField(
        default=date.today,
        verbose_name="日期"
    )
    class_type = models.CharField(
        max_length=100,
        choices=ClassTypeList.choices,
        default=ClassTypeList.TRAINING,
        verbose_name="班级"
    )
    log_file = models.FileField(
        upload_to=user_dierctory_path,
        storage=OverwriteStorage(),
        null=False,
        # unique=True,
        help_text="只能上传pdf格式的文件。",
        verbose_name="文件"
    )
    module_list = models.CharField(
        max_length=100,
        choices=MODULE_LIST,
        default="ModuleA",
        verbose_name="模块"
    )
    uploaded_date = models.DateTimeField(
        auto_now_add=True,
        verbose_name="上传时间"
    )

    class Meta:
        ordering = ('-log_date', '-uploaded_date',)

    def log_file_name(self):
        return path.basename(self.log_file.name)

    def class_type_name(self):
        return ClassTypeList(self.class_type).label



    # def __str__(self):
    #     return self.author_name

class TlogEvaluate(models.Model):
    tlog = models.ForeignKey(LogUploadModel, on_delete=models.CASCADE)
    evaluate_score = models.IntegerField(
        default=0,
        verbose_name="评分"
    )
    evaluate_content = models.CharField(
        max_length=100,
        default="",
        verbose_name="评论"
    )
    evaluate_time = models.DateTimeField(
        auto_now_add=True,
        verbose_name="评价时间"
    )
    evaluate_coach = models.ForeignKey(
        'accounts.User',
        on_delete=models.CASCADE,
        verbose_name="评价教练"
    )

itnsa/accounts/forms.py
from dataclasses import field
from django import forms
from django.contrib.auth.forms import UserCreationForm

from .models import User


class RegisterForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'password1', 'password2', 'email', 'real_name', 'phone_number', 'is_student', 'is_coach', 'is_competitor']
        widgets = {
            'username': forms.TextInput(attrs={'class': 'form-control'}),
            'password1': forms.PasswordInput(attrs={'class': 'form-control'}),
            'password2': forms.PasswordInput(attrs={'class': 'form-control'}),
            'email': forms.EmailInput(attrs={'class': 'form-control'}),
            'real_name': forms.TextInput(attrs={'class': 'form-control'}),
            'phone_number': forms.TextInput(attrs={'class': 'form-control'}),
            'is_student': forms.CheckboxInput(attrs={'class': 'form-check-input'}),
            'is_coach': forms.CheckboxInput(attrs={'class': 'form-check-input'}),
            'is_competitor': forms.CheckboxInput(attrs={'class': 'form-check-input'}),
        }

itnsa/accounts/views.py
from django.shortcuts import render, redirect

# Create your views here.

from .forms import RegisterForm


def register(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('admin:login')
    else:
        form = RegisterForm()
    return render(request, 'accounts/register.html', {'form': form, 'heading': '用户注册'})

itnsa/home/views.py
from django.views import generic

# Create your views here.

class HomePage(generic.TemplateView):
    
    template_name = 'home/home.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Home'
        return context




class AboutPage(generic.TemplateView):
    
    template_name = 'home/about.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'About'
        return context

itnsa/tlog/views.py
from django.shortcuts import render

# Create your views here.

itnsa/accounts/templates/accounts/register.html
{% extends 'base.html' %}

{% block content %}

<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}

    <div class="mt-3">
        <input class="btn btn-info me-2" type="submit" value="注册">
        <input class="btn btn-info" type="reset" value="重置">
    </div>

    {% endblock content %}

itnsa/home/templates/home/about.html
{% extends 'base.html' %}

{% block content %}

{{ context }}

{% endblock content %}

itnsa/home/templates/home/home.html
{% extends 'base.html' %}

{% block content %}

{{ context }}

{% endblock content %}

itnsa/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="zh-hans">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="ITNSA">
    <meta name="author" content="hdaojin">
    <link rel="shortcut icon" href="{% static 'site/ico/favicon.ico' %}">

    <title> {% if heading %}{{ heading }}{% endif %} | ITNSA </title>
    
    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}" type="text/css">
    
    <!-- Custom styles for this template -->
    <link href="{% static 'site/css/style.css' %}" rel="stylesheet" type="text/css">

    <!--[if lt IE 9]>
            <script src="https://cdn.static.runoob.com/libs/html5shiv/3.7/html5shiv.min.js"></script>
    <![endif]-->

</head>

<body>
    {% include 'header.html' %}
    <main style="margin-top:80px">
        <div class="container-fluid">
            <div class="pb-2 px-5">
                <h1>{% block h1 %} {% if heading %}{{ heading }}{% endif %} {% endblock %}</h1>
            </div>
            <div class="py-3 px-5">
                {% block content %}
                {% endblock content %}
            </div>
        </div>
    </main>
    {% include 'footer.html' %}

{% block javascript %}
    <!-- some javascript -->
{% endblock %}

    <!-- <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script> -->
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
</body>

</html>

itnsa/templates/footer.html
<footer class="py-3 my-4">
    <ul class="nav justify-content-center border-bottom pb-3 mb-3">
        <li class="nav-item"><a href="/" class="nav-link px-2 text-muted">Home</a></li>
        <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">About</a></li>
    </ul>
    <p class="text-center text-muted">&copy; 2022 itnsa.cn</p>
    <p class="text-center text-muted"><a href="https://beian.miit.gov.cn/" class="text-decoration-none link-secondary" target="_blank">粤ICP备2022011003号-1</a></p>
</footer>

itnsa/templates/header.html
{% url 'home:home' as home_url %}
{% url 'home:about' as about_url %}
{% url 'accounts:register' as register_url %}
{% url 'admin:login' as login_url %}
{% url 'tlog:upload' as tlog_upload_url %}
{% url 'tlog:list' as tlog_list_url %}


<!-- 定义导航栏 -->
<header class="container-fluid p-2 bg-dark text-white fixed-top">
    <!-- <div class="container-lg"> -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark mx-5 ">
        <div class="d-flex container-fluid">
            <!-- 导航栏LOGO -->
            <a class="navbar-brand" href="#">ITNSA</a>

            <!-- 导航栏折叠按钮 -->
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#collapsiableNavbar">
                <span class="navbar-toggler-icon"></span>
            </button>

            <!-- 导航栏条目 -->
            <div class="collapse navbar-collapse" id="collapsiableNavbar">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link {% if request.path_info == home_url %} active {% endif %}"
                            aria-current="page" href="{{ home_url }}">首页</a>
                    </li>

                    <!-- 集训管理 -->
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle {% if request.path_info == tlog_upload_url or request.path_info == tlog_list_url %} active {% endif %}"
                            data-bs-toggle="dropdown" href="#" role="button" aria-expanded="false">集训管理</a>
                        <ul class="dropdown-menu">
                            <li><a class="dropdown-item" href="{{ tlog_upload_url }}">日志上传</a></li>
                            <li><a class="dropdown-item" href="{{ tlog_list_url }}">日志列表</a></li>
                            <li><a class="dropdown-item" href="#">考勤签到</a></li>
                        </ul>
                    </li>

                    <!-- 关于 -->
                    <li class="nav-item">
                        <a class="nav-link {% if request.path_info == about_url %} active {% endif %}"
                            href="{{ about_url }}">关于</a>
                    </li>
                </ul>

                <!-- 搜索框 -->
                <div class="navbar-nav">
                    <form class="me-3">
                        <input type="search" class="form-control" placeholder="Search..." aria-label="Search">
                    </form>

                    <!-- 注册登录 -->
                    <a href="{{ login_url }}"><button type="button" class="btn btn-outline-light me-3">登录</button></a>
                    <a href="{{ register_url }}"><button type="button" class="btn btn-warning">注册</button></a>
                </div>
            </div>
        </div>
    </nav>
    <!-- </div> -->
</header>